export const PICKER_SYNC_SET_SELECTED_UNIVERSIDADE = 'PICKER_SYNC_SET_SELECTED_UNIVERSIDADE'
export const PICKER_SYNC_SET_SELECTED_UNIDADE = 'PICKER_SYNC_SET_SELECTED_UNIDADE'
export const PICKER_SYNC_SET_SELECTED_CURSO = 'PICKER_SYNC_SET_SELECTED_CURSO'
export const PICKER_SYNC_SET_SELECTED_TURMA = 'PICKER_SYNC_SET_SELECTED_TURMA'
export const PICKER_SYNC_SET_SELECTED_DISCIPLINA = 'PICKER_SYNC_SET_SELECTED_DISCIPLINA'

export const PICKER_SYNC_PROMISES_LOADED = 'PICKER_SYNC_PROMISES_LOADED'
export const setPromisesLoaded = (loaded, result) => ({ type: PICKER_SYNC_PROMISES_LOADED, loaded, result })
